name: Set OpenAI API Key

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  set-env:
    runs-on: ubuntu-latest

    steps:
    - name: Set OpenAI API Key
      env:
        NEXT_PUBLIC_OPENAI_KEY: ${{ secrets.NEXT_PUBLIC_OPENAI_KEY }}
        NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
        GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
      run: echo "Setting API Key"
